<?php

/**
 * @file
 * Primary module hooks for Superfish - ARIA module.
 */

function superfish_aria_theme_suggestions_superfish_menu_items_alter(array &$suggestions, array $variables) {
    
    $suggestions[] = 'superfish_menu_items__superfish_aria_menu_items';
    
}

function superfish_aria_theme() {
    return [
        'superfish_menu_items__superfish_aria_menu_items' => [
            'template' => 'superfish-menu-items--superfish-aria-menu-items',
            'render element' => 'element',
            'base hook' => 'superfish_menu_items',
        ]
    ];
}


/**
 * 
 * Implements hook_page_attachments()
 */
function superfish_aria_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'superfish_aria/global-scripts';
}
 